Develop
worldbank/stata-linter pull request #32
Opened 2022-01-04 13:10 UTC by luizaandrade

I think this is ready for publication!!! \o/

2022-01-12 16:33 UTC, luisesanmartin approved these changes
@luizaandrade I'm merging these changes to main. I also changed the readme file so it's in line with the options we now have

2022-03-12 00:25 UTC, luisesanmartin commented
@kbjarkefur the code in this branch is ready for review

2022-07-18 23:08 UTC, luisesanmartin commented
@bbdaniels this is ready for review. Note that all the issues with the tag `v1.0` should be solved in this branch

2022-07-29 20:13 UTC, bbdaniels commented
- [ ] Runfile crash:
```
.   // Lint with results in excel file
.   lint "${test_dir}/bad.do", nosummary          ///
>     excel("${test_dir}/detect_lint.xlsx")

Linting file: /Users/bbdaniels/GitHub/stata-linter/test/bad.do


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bbdaniels/Library/Application Support/Stata/ado/plus/py/stata_linter_detect.py", line 739, in stata_linter_detect_py
    with pd.ExcelWriter(excel) as writer:
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
r(7102);
```

2022-07-29 20:14 UTC, bbdaniels commented
- [ ] Hard tabs do not appear to be replaced except when they are at the beginning of a line, leading to odd spacing after partial correctio
<img width="1439" alt="Screen Shot(3)" src="https://user-images.githubusercontent.com/1459122/181836622-178f45a0-30fc-44d9-913b-7b77983b33ac.png">
n

2022-07-29 20:17 UTC, bbdaniels commented
- [ ] Confirming this is intentional: long lines are not broken when they fall inside functions. If correct, please add note to helpfile confirming exceptions

<img width="1641" alt="Screen Shot" src="https://user-images.githubusercontent.com/1459122/181837013-8a420b2c-5ce0-4095-b142-a3e86f765170.png">

2022-07-29 20:21 UTC, bbdaniels commented
- [ ] Line lengths remain too long after correction, possibly a collision here with hard tab replacement plus the extra characters from `\\\`

<img width="1415" alt="Screen Shot(4)" src="https://user-images.githubusercontent.com/1459122/181837536-dd7b4e4c-edc9-4d9e-934a-c720eed4cd01.png">

2022-07-29 20:22 UTC, bbdaniels commented
- [ ] Add informative error when invalid response given

![Screen Shot(5)](https://user-images.githubusercontent.com/1459122/181837750-14a6f043-24b5-4954-acc2-43bf298c6f98.png)

2022-07-29 20:24 UTC, bbdaniels commented
- [ ] Hard tabs not replaced within comments

<img width="1000" alt="Screen Shot(6)" src="https://user-images.githubusercontent.com/1459122/181837967-2c1fbb79-9bf1-4b23-81e1-51e3082d9dc7.png">

2022-07-29 20:26 UTC, bbdaniels commented
- [ ] `detect` function flags math symbols within `" "` when it should not do so; `correct` ignores them

2022-07-29 20:29 UTC, bbdaniels commented
- [ ] Existing indentation is not respected in re-indentation function

<img width="1601" alt="Screen Shot(7)" src="https://user-images.githubusercontent.com/1459122/181838569-cd2e8e04-d92f-4665-bdf2-c06e2f595600.png">

2022-07-29 20:41 UTC, bbdaniels commented
- [ ] `inprep` is an unusual option name that is not intuitive, why isn't this something like `force`?

2022-07-29 20:45 UTC, bbdaniels commented
- [ ] The help file should separate clearly what issues are only caught in detection and which issues are actually corrected, and what corrections are and are not done

2022-07-29 20:48 UTC, bbdaniels commented
- [ ] The help file should also note common confusions that the code cannot distinguish. For example, under "Check if backslashes are not used in file paths", the code is only looking for backslashes in general because it cannot tell what is a file path. Therefore these are "flags" that could be errors, but cannot be accurately detected by the code and cannot be corrected. More description for each of these items in this line would be useful.

2022-07-29 20:49 UTC, bbdaniels requested changes
Ok I have tested this as thoroughly as I can -- most of the functionality looks to be in very good shape. I caught a few edge cases in my runs as flagged above, and I think the help file could use a little more explanation of each of the tests and what the command does and does not do for each one. I am pushing some minor changes to the first part of the help file.

2022-08-04 19:07 UTC, luisesanmartin commented
> * [ ]  Runfile crash, looks like a Python dependency issue:
> 
> 
> ```
> .   // Lint with results in excel file
> .   lint "${test_dir}/bad.do", nosummary          ///
> >     excel("${test_dir}/detect_lint.xlsx")
> 
> Linting file: /Users/bbdaniels/GitHub/stata-linter/test/bad.do
> 
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/bbdaniels/Library/Application Support/Stata/ado/plus/py/stata_linter_detect.py", line 739, in stata_linter_detect_py
>     with pd.ExcelWriter(excel) as writer:
>   File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
>     from openpyxl.workbook import Workbook
> ModuleNotFoundError: No module named 'openpyxl'
> r(7102);
> ```

@bbdaniels when have time, can you pull from this branch and try again? it should a message saying that you need to install the Python package `openpyxl`

2022-08-04 22:14 UTC, luisesanmartin commented
> * [ ]  Hard tabs do not appear to be replaced when they are not at the beginning of a line, leading to odd spacing after partial correction
> 
> 
> <img alt="Screen Shot(3)" width="1439" src="https://user-images.githubusercontent.com/1459122/181836622-178f45a0-30fc-44d9-913b-7b77983b33ac.png">

corrected in faa55e1

2022-08-04 22:24 UTC, luisesanmartin commented
> * [x]  Confirming this is intentional: long lines are not broken when they fall inside functions. If correct, please add note to helpfile confirming exceptions
> 
> 
> <img alt="Screen Shot" width="1641" src="https://user-images.githubusercontent.com/1459122/181837013-8a420b2c-5ce0-4095-b142-a3e86f765170.png">

yes, this is intentional. Lines are not split in white spaces inside parentheses, curly brackets, or double quotes. Added a clarification on this in 2552456

2022-08-05 00:24 UTC, luisesanmartin commented
> * [x]  Line lengths remain too long after correction, possibly a collision here with hard tab replacement plus the extra characters from `///`
> 
> 
> <img alt="Screen Shot(4)" width="1415" src="https://user-images.githubusercontent.com/1459122/181837536-dd7b4e4c-edc9-4d9e-934a-c720eed4cd01.png">

thanks, this was actually a bug that I hadn't detected. It was corrected in 7d238e0

2022-08-05 00:45 UTC, luisesanmartin commented
> * [x]  Add informative error when invalid response given
> 
> 
> ![Screen Shot(5)](https://user-images.githubusercontent.com/1459122/181837750-14a6f043-24b5-4954-acc2-43bf298c6f98.png)

added in 97ca9dd
![image](https://user-images.githubusercontent.com/38444484/182978419-53857779-9bc1-497f-8747-f56f623c69b3.png)

2022-08-05 00:51 UTC, luisesanmartin commented
> * [x]  Hard tabs not replaced within comments
> 
> 
> <img alt="Screen Shot(6)" width="1000" src="https://user-images.githubusercontent.com/1459122/181837967-2c1fbb79-9bf1-4b23-81e1-51e3082d9dc7.png">

corrected in 5aad6d9

2022-11-04 21:00 UTC, luisesanmartin commented
> * [x]  `detect` function flags math symbols within `" "` when it should not do so; `correct` ignores them

corrected the function in 2de4ca8 so `detect` knows which portions of a line are not within quotes

2022-12-04 18:56 UTC, luisesanmartin commented
> * [ ]  Existing indentation is not respected in re-indentation function
> 
> 
> <img alt="Screen Shot(7)" width="1601" src="https://user-images.githubusercontent.com/1459122/181838569-cd2e8e04-d92f-4665-bdf2-c06e2f595600.png">

Checking this was challenging but I could finally detect what was wrong. A few comments:
- specifically in this case, the command is checking which lines inside the loop don't have the correct loop indentation, which by default is 4. Then it's moving every line that doesn't have at least a 4-indentation inside the loop so they have an indentation of 4 + the indentation of the line that opens the loop. Since you're using an indentation of 2, your case would have worked better with the option `indentation(2)` which changes the default of 4
- That said, the correction of indentation only works with respect of the indentation of the line that opens the loop. In short, it will check which lines inside the loop don't have an indentation of at least (indentation of opening line) + (indentation level -- 4 by default) and will change their indentation to that number if theirs is lower. Correction of indentation doesn't work with respect of any extra indentation that should be ideally added because the previous line ended with a `///`, which I understand is what you were testing with this command. Bad indentations with respect of continued lines (`///`) are only flagged in the detection function, but they are not corrected. We might add that functionality in a later version though
- Reviewing the code for this comment made me discover a bug: the command was only checking the correct indentation of the first non-blank line of the loop. Now it checks all the lines until it's closed and works well with embedded loops (added in 6119628)

2022-12-04 20:28 UTC, luisesanmartin commented
> * [x]  `inprep` is an unusual option name that is not intuitive, why isn't this something like `force`?

corrected in 5f83d6f

2022-12-06 11:29 UTC, kbjarkefur commented on src/lint.ado
> +				display as result 	`"{phang}For more information about coding guidelines visit the {browse "https://https://dimewiki.worldbank.org/Stata_Linter":Stata linter wiki.}{p_end}"'
```suggestion
				display as result 	`"{phang}For more information about coding guidelines visit the {browse "https://dimewiki.worldbank.org/Stata_Linter":Stata linter wiki.}{p_end}"'
```

2022-12-06 14:49 UTC, kbjarkefur commented on LICENSE
> +Copyright (c) 2022 Mizuhiro Suzuki, World Bank Group.
```suggestion
Copyright (c) DIME Analytics, DIME, DEC, The World Bank Group.
```
I saw my name was listed on `ietoolkit`. That is not right. All these licenses should be DA, DIME, WB.

2022-12-06 15:42 UTC, merged